# Generated by Django 6.0.4 on 2026-04-13 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('desc', models.CharField(max_length=1000)),
                ('photo', models.CharField(blank=True, max_length=1000, null=True)),
                ('popularity', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('duration', models.CharField(blank=True, max_length=50, null=True)),
                ('likes', models.IntegerField(default=0)),
                ('rating', models.CharField(default='0/10', max_length=10)),
                ('short_description', models.CharField(blank=True, max_length=255, null=True)),
                ('poster', models.URLField(blank=True, null=True)),
                ('backdrop', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('videoUrl', models.URLField(blank=True, null=True)),
                ('actors', models.ManyToManyField(related_name='movies', to='movies.actor')),
                ('categories', models.ManyToManyField(related_name='movies', to='movies.category')),
            ],
        ),
    ]
