# Generated by Django 6.0.4 on 2026-04-18 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_remove_movie_likes_remove_movie_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='api_likes',
            field=models.IntegerField(default=0),
        ),
    ]
