# Generated by Django 6.0.3 on 2026-04-19 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_api_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='is_watched',
            field=models.BooleanField(default=False),
        ),
    ]
