# Generated by Django 6.0.3 on 2026-04-19 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movie_is_watched'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='is_watched',
        ),
    ]
