# Generated by Django 6.0.4 on 2026-04-13 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_movie_backdrop_alter_movie_poster_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('desc', models.CharField(max_length=1000)),
                ('photo', models.CharField(blank=True, max_length=1000, null=True)),
                ('popularity', models.FloatField(default=0.0)),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(related_name='movies', to='movies.actor'),
        ),
    ]
