# Generated by Django 6.0.4 on 2026-04-24 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_remove_movie_is_watched'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='liked_by',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='liked_by',
        ),
    ]
